[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
basic_storage = "HTfqYyFeQgM6nzGfDWWVTJwrPVRJu23YG51zT7gn9isA"
data_reader = "2mdpoj8AzV6o8YEaKE6oRurnHkS1J4LmFYM2phDx2fmA"
day_1 = "AyoQw58UPLqi5gKuhzYTi4Kcd9BcfxNuetUv95p6vdMo"
example_map = "GR9RF1G4JjrHMRPeG1hkv15yLWucbR9fHw2RkKR6r9jT"
pda_example = "5b3FiHezoqkM17jBf6YiEE3pYqDvfYbFNGuQ8mg2GdJS"
relloc_example = "D9fCPfoPDbzNZmPXSetSveWP9755z3RnMLh2kvPttWbP"
sol_transfer = "YYiXCTU8vjgiXB85Cod7vi3V5rmY73kYuZW6zDAwkdq"
sysvars = "F9fPdvxQsdKLeHjfQe5Jb2fsBZWyH5zBKgFmm6VJnrGw"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/Users/valekar/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
