[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
day_1 = "AyoQw58UPLqi5gKuhzYTi4Kcd9BcfxNuetUv95p6vdMo"
sysvars = "F9fPdvxQsdKLeHjfQe5Jb2fsBZWyH5zBKgFmm6VJnrGw"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/Users/valekar/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
